#pragma once

#include "Def_CompileOption.h"

#if(GET_INSPECTOR == SYS_OQC_SFR_MULTI_CL)
//-------------------------------------------------------------------------
// DIO
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("파워 온"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("초기화 버튼"),
	_T("긴급정지버튼"),
	_T("에어 오프"),
	_T("안전 센서1"),
	_T("-"),
	_T("카메라 감지 센서"),
	_T("-"),
	_T("-"),
	_T("슬립모드 센서"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브핀 내림"),

	_T("도어 인터락 열림/닫힘(전면)"),
	_T("도어 인터락 열림/닫힘(좌측1)"),
	_T("도어 인터락 열림/닫힘(좌측2)"),
	_T("도어 인터락 열림/닫힘(우측1)"),
	_T("도어 인터락 열림/닫힘(우측2)"),
	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("소켓 In"),
	_T("소켓 Out"),
	_T("소켓 올림"),
	_T("소켓 내림"),
};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("Power On"),
	_T("START"),
	_T("STOP"),
	_T("INIT"),
	_T("EMO"),
	_T("Air Down"),
	_T("Area Sensor1"),
	_T("-"),
	_T("Camera Detect Sensor"),
	_T("-"),
	_T("-"),
	_T("Sleep Mode On Sensor"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door Open/Close Sensor(Front)"),
	_T("Door Open/Close Sensor(Left1)"),
	_T("Door Open/Close Sensor(Left2)"),
	_T("Door Open/Close Sensor(Right1)"),
	_T("Door Open/Close Sensor(Right2)"),
	_T("Door Open/Close Sensor(Back1)"),
	_T("Door Open/Close Sensor(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Socket In"),
	_T("Socket Out"),
	_T("Socket Up"),
	_T("Socket Down"),
};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("시작 버튼 램프"),
	_T("정지 버튼 램프"),
	_T("초기화 버튼 램프"),
	_T("리셋 버튼 램프"),
	_T("영상보드 On/Off"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("슬립모드 On"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브 핀 내림"),

	_T("도어 인터락 On/Off(전면)"),
	_T("도어 인터락 On/Off(좌측1)"),
	_T("도어 인터락 On/Off(좌측2)"),
	_T("도어 인터락 On/Off(우측1)"),
	_T("도어 인터락 On/Off(우측2)"),
	_T("도어 인터락 On/Off(후면1)"),
	_T("도어 인터락 On/Off(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("소켓 In"),
	_T("소켓 Out"),
	_T("소켓 올림"),
	_T("소켓 내림"),
};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("START LAMP"),
	_T("STOP LAMP"),
	_T("INIT LAMP"),
	_T("RESET LAMP"),
	_T("-"),
	_T("TOWERLAMP RED"),
	_T("TOWERLAMP YELLOW"),
	_T("TOWERLAMP GREEN"),
	_T("TOWERLAMP BEEP1"),
	_T("TOWERLAMP BEEP2"),
	_T("Sleep Mode On"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door InterLock(Front)"),
	_T("Door InterLock(Left1)"),
	_T("Door InterLock(Left2)"),
	_T("Door InterLock(Right1)"),
	_T("Door InterLock(Right2)"),
	_T("Door InterLock(Bakc1)"),
	_T("Door InterLock(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Socket In"),
	_T("Socket Out"),
	_T("Socket Up"),
	_T("Socekt Down"),
};

// IO LIST INPUT
enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_POWER = 0,
	DIO_INPUT_X0_01_START,
	DIO_INPUT_X0_02_STOP,
	DIO_INPUT_X0_03_INIT,
	DIO_INPUT_X0_04_EMO,
	DIO_INPUT_X0_05_MAINAIR,
	DIO_INPUT_X0_06_AREASENSOR1,
	DIO_INPUT_X0_07_SPARE,
	DIO_INPUT_X0_08_CAMERA_DETECT_SENSOR, //Camera Detect Sensor
	DIO_INPUT_X0_09_SPARE,
	DIO_INPUT_X0_0A_SPARE,
	DIO_INPUT_X0_0B_SLEEPMODE_ON_SENSOR,
	DIO_INPUT_X0_0C_CAMERA_FIX_CYL_ON,
	DIO_INPUT_X0_0D_CAMERA_FIX_CYL_OFF,
	DIO_INPUT_X0_0E_PROBEPIN_UP,
	DIO_INPUT_X0_0F_PROBEPIN_DOWN,

	DIO_INPUT_X0_10_FRONT_DOORLOCK_OPENCLOSE,
	DIO_INPUT_X0_11_LEFT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_12_LEFT_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_13_RIGHT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_14_RIGHT_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_15_BACK_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_16_BACK_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_17_SPARE,
	DIO_INPUT_X0_18_SPARE,
	DIO_INPUT_X0_19_SPARE,
	DIO_INPUT_X0_1A_SPARE,
	DIO_INPUT_X0_1B_SPARE,
	DIO_INPUT_X0_1C_SOCKET_IN,
	DIO_INPUT_X0_1D_SOCKET_OUT,
	DIO_INPUT_X0_1E_SOCKET_UP,
	DIO_INPUT_X0_1F_SOCKET_DOWN,
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_02_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_03_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_04_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_SPARE,
	DIO_OUTPUT_Y0_06_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_07_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_08_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_09_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_0A_TOWERLAMP_BEEP2,
	DIO_OUTPUT_Y0_0B_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_0C_CAMERA_FIX_CYL_ON,
	DIO_OUTPUT_Y0_0D_CAMERA_FIX_CYL_OFF,
	DIO_OUTPUT_Y0_0E_PROBEPIN_CYLINDER_UP,
	DIO_OUTPUT_Y0_0F_PROBEPIN_CYLINDER_DOWN,

	DIO_OUTPUT_Y0_10_DOORLOCK_ONOFF_FRONT,
	DIO_OUTPUT_Y0_11_DOORLOCK_ONOFF_LEFT1,
	DIO_OUTPUT_Y0_12_DOORLOCK_ONOFF_LEFT2,
	DIO_OUTPUT_Y0_13_DOORLOCK_ONOFF_RIGHT1,
	DIO_OUTPUT_Y0_14_DOORLOCK_ONOFF_RIGHT2,
	DIO_OUTPUT_Y0_15_DOORLOCK_ONOFF_BACK1,
	DIO_OUTPUT_Y0_16_DOORLOCK_ONOFF_BACK2,
	DIO_OUTPUT_Y0_17_SPARE,
	DIO_OUTPUT_Y0_18_SPARE,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_1A_SPARE,
	DIO_OUTPUT_Y0_1B_SPARE,
	DIO_OUTPUT_Y0_1C_SOCKET_IN,
	DIO_OUTPUT_Y0_1D_SOCKET_OUT,
	DIO_OUTPUT_Y0_1E_SOCKET_UP,
	DIO_OUTPUT_Y0_1F_SOCKET_DOWN,
};
#elif (GET_INSPECTOR == SYS_OQC_SFR_SINGLE_CL)
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("파워 온"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("초기화 버튼"),
	_T("긴급정지버튼"),
	_T("에어 오프"),
	_T("안전 센서1"),
	_T("-"),
	_T("카메라 감지 센서"),
	_T("-"),
	_T("-"),
	_T("슬립모드 센서"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브핀 내림"),

	_T("도어 인터락 열림/닫힘(전면)"),
	_T("도어 인터락 열림/닫힘(좌측1)"),
	_T("도어 인터락 열림/닫힘(좌측2)"),
	_T("도어 인터락 열림/닫힘(우측1)"),
	_T("도어 인터락 열림/닫힘(우측2)"),
	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("소켓 커버 Open"),
	_T("소켓 In"),
	_T("소켓 Out"),
	_T("소켓 올림"),
	_T("소켓 내림"),
};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("Power On"),
	_T("START"),
	_T("STOP"),
	_T("INIT"),
	_T("EMO"),
	_T("Air Down"),
	_T("Area Sensor1"),
	_T("-"),
	_T("Camera Detect Sensor"),
	_T("-"),
	_T("-"),
	_T("Sleep Mode On Sensor"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door Open/Close Sensor(Front)"),
	_T("Door Open/Close Sensor(Left1)"),
	_T("Door Open/Close Sensor(Left2)"),
	_T("Door Open/Close Sensor(Right1)"),
	_T("Door Open/Close Sensor(Right2)"),
	_T("Door Open/Close Sensor(Back1)"),
	_T("Door Open/Close Sensor(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Socket Cover Open"),
	_T("Socket In"),
	_T("Socket Out"),
	_T("Socket Up"),
	_T("Socket Down"),
};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("시작 버튼 램프"),
	_T("정지 버튼 램프"),
	_T("초기화 버튼 램프"),
	_T("리셋 버튼 램프"),
	_T("영상보드 On/Off"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("슬립모드 On"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브 핀 내림"),

	_T("도어 인터락 On/Off(전면)"),
	_T("도어 인터락 On/Off(좌측1)"),
	_T("도어 인터락 On/Off(우측1)"),
	_T("도어 인터락 On/Off(후면1)"),
	_T("도어 인터락 On/Off(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("소켓 In"),
	_T("소켓 Out"),
	_T("소켓 올림"),
	_T("소켓 내림"),
};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("START LAMP"),
	_T("STOP LAMP"),
	_T("INIT LAMP"),
	_T("RESET LAMP"),
	_T("-"),
	_T("TOWERLAMP RED"),
	_T("TOWERLAMP YELLOW"),
	_T("TOWERLAMP GREEN"),
	_T("TOWERLAMP BEEP1"),
	_T("TOWERLAMP BEEP2"),
	_T("Sleep Mode On"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door InterLock(Front)"),
	_T("Door InterLock(Left1)"),
	_T("Door InterLock(Right1)"),
	_T("Door InterLock(Back1)"),
	_T("Door InterLock(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Socket In"),
	_T("Socket Out"),
	_T("Socket Up"),
	_T("Socekt Down"),
};

// IO LIST INPUT
enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_POWER = 0,
	DIO_INPUT_X0_01_START,
	DIO_INPUT_X0_02_STOP,
	DIO_INPUT_X0_03_INIT,
	DIO_INPUT_X0_04_EMO,
	DIO_INPUT_X0_05_MAINAIR,
	DIO_INPUT_X0_06_AREASENSOR1,
	DIO_INPUT_X0_07_SPARE,
	DIO_INPUT_X0_08_CAMERA_DETECT_SENSOR, //Camera Detect Sensor
	DIO_INPUT_X0_09_SPARE,
	DIO_INPUT_X0_0A_SPARE,
	DIO_INPUT_X0_0B_SLEEPMODE_ON_SENSOR,
	DIO_INPUT_X0_0C_CAMERA_FIX_CYL_ON,
	DIO_INPUT_X0_0D_CAMERA_FIX_CYL_OFF,
	DIO_INPUT_X0_0E_PROBEPIN_UP,
	DIO_INPUT_X0_0F_PROBEPIN_DOWN,

	DIO_INPUT_X0_10_FRONT_DOORLOCK_OPENCLOSE,
	DIO_INPUT_X0_11_LEFT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_12_RIGHT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_13_BACK_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_14_BACK_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_15_SPARE,
	DIO_INPUT_X0_16_SPARE,
	DIO_INPUT_X0_17_SPARE,
	DIO_INPUT_X0_18_SPARE,
	DIO_INPUT_X0_19_SPARE,
	DIO_INPUT_X0_1A_SPARE,
	DIO_INPUT_X0_1B_SOCKET_COVER_OPEN,
	DIO_INPUT_X0_1C_SOCKET_IN,
	DIO_INPUT_X0_1D_SOCKET_OUT,
	DIO_INPUT_X0_1E_SOCKET_UP,
	DIO_INPUT_X0_1F_SOCKET_DOWN,
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_02_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_03_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_04_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_SPARE,
	DIO_OUTPUT_Y0_06_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_07_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_08_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_09_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_0A_TOWERLAMP_BEEP2,
	DIO_OUTPUT_Y0_0B_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_0C_CAMERA_FIX_CYL_ON,
	DIO_OUTPUT_Y0_0D_CAMERA_FIX_CYL_OFF,
	DIO_OUTPUT_Y0_0E_PROBEPIN_CYLINDER_UP,
	DIO_OUTPUT_Y0_0F_PROBEPIN_CYLINDER_DOWN,

	DIO_OUTPUT_Y0_10_DOORLOCK_ONOFF_FRONT,
	DIO_OUTPUT_Y0_11_DOORLOCK_ONOFF_LEFT1,
	DIO_OUTPUT_Y0_12_DOORLOCK_ONOFF_RIGHT1,
	DIO_OUTPUT_Y0_13_DOORLOCK_ONOFF_BACK1,
	DIO_OUTPUT_Y0_14_DOORLOCK_ONOFF_BACK2,
	DIO_OUTPUT_Y0_15_SPARE,
	DIO_OUTPUT_Y0_16_SPARE,
	DIO_OUTPUT_Y0_17_SPARE,
	DIO_OUTPUT_Y0_18_SPARE,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_1A_SPARE,
	DIO_OUTPUT_Y0_1B_SPARE,
	DIO_OUTPUT_Y0_1C_SOCKET_IN,
	DIO_OUTPUT_Y0_1D_SOCKET_OUT,
	DIO_OUTPUT_Y0_1E_SOCKET_UP,
	DIO_OUTPUT_Y0_1F_SOCKET_DOWN,
};
// IO Dlg End
//-------------------------------------------------------------------------
#elif (GET_INSPECTOR == SYS_DISTORTION_30)
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("파워 온"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("초기화 버튼"),
	_T("긴급정지버튼"),
	_T("에어 오프"),
	_T("안전 센서1"),
	_T("-"),
	_T("소켓 열림/닫힘 센서1"),
	_T("소켓 열림/닫힘 센서2"),
	_T("-"),
	_T("슬립모드 센서"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브핀 내림"),

	_T("도어 인터락 열림/닫힘(전면)"),
	_T("도어 인터락 열림/닫힘(좌측1)"),
	_T("도어 인터락 열림/닫힘(좌측2)"),
	_T("도어 인터락 열림/닫힘(우측1)"),
	_T("도어 인터락 열림/닫힘(우측2)"),
	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("Power On"),
	_T("START"),
	_T("STOP"),
	_T("INIT"),
	_T("EMO"),
	_T("Air Down"),
	_T("Area Sensor1"),
	_T("-"),
	_T("Manual Socket Open/Close1"),
	_T("Manual Socket Open/Close2"),
	_T("-"),
	_T("Sleep Mode On Sensor"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door Open/Close Sensor(Front)"),
	_T("Door Open/Close Sensor(Left1)"),
	_T("Door Open/Close Sensor(Left2)"),
	_T("Door Open/Close Sensor(Right1)"),
	_T("Door Open/Close Sensor(Right2)"),
	_T("Door Open/Close Sensor(Back1)"),
	_T("Door Open/Close Sensor(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("시작 버튼 램프"),
	_T("정지 버튼 램프"),
	_T("초기화 버튼 램프"),
	_T("리셋 버튼 램프"),
	_T("-"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("슬립모드 On"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브 핀 내림"),

	_T("도어 인터락 On/Off(전면)"),
	_T("도어 인터락 On/Off(좌측1)"),
	_T("도어 인터락 On/Off(좌측2)"),
	_T("도어 인터락 On/Off(우측1)"),
	_T("도어 인터락 On/Off(우측2)"),
	_T("도어 인터락 On/Off(후면1)"),
	_T("도어 인터락 On/Off(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("START LAMP"),
	_T("STOP LAMP"),
	_T("INIT LAMP"),
	_T("RESET LAMP"),
	_T("-"),
	_T("TOWERLAMP RED"),
	_T("TOWERLAMP YELLOW"),
	_T("TOWERLAMP GREEN"),
	_T("TOWERLAMP BEEP1"),
	_T("TOWERLAMP BEEP2"),
	_T("Sleep Mode On"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door InterLock(Front)"),
	_T("Door InterLock(Left1)"),
	_T("Door InterLock(Left2)"),
	_T("Door InterLock(Right1)"),
	_T("Door InterLock(Right2)"),
	_T("Door InterLock(Bakc1)"),
	_T("Door InterLock(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
};

// IO LIST INPUT
enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_POWER = 0,
	DIO_INPUT_X0_01_START,
	DIO_INPUT_X0_02_STOP,
	DIO_INPUT_X0_03_INIT,
	DIO_INPUT_X0_04_EMO,
	DIO_INPUT_X0_05_MAINAIR,
	DIO_INPUT_X0_06_AREASENSOR1,
	DIO_INPUT_X0_07_SPARE,
	DIO_INPUT_X0_08_MANUALSOCEKT_OPENCLOSE1,
	DIO_INPUT_X0_09_MANUALSOCEKT_OPENCLOSE2,
	DIO_INPUT_X0_0A_SPARE,
	DIO_INPUT_X0_0B_SLEEPMODE_ON_SENSOR,
	DIO_INPUT_X0_0C_CAMERA_FIX_CYL_ON,
	DIO_INPUT_X0_0D_CAMERA_FIX_CYL_OFF,
	DIO_INPUT_X0_0E_PROBEPIN_UP,
	DIO_INPUT_X0_0F_PROBEPIN_DOWN,

	DIO_INPUT_X0_10_FRONT_DOORLOCK_OPENCLOSE,
	DIO_INPUT_X0_11_LEFT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_12_LEFT_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_13_RIGHT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_14_RIGHT_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_15_BACK_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_16_BACK_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_17_SPARE,
	DIO_INPUT_X0_18_SPARE,
	DIO_INPUT_X0_19_SPARE,
	DIO_INPUT_X0_1A_SPARE,
	DIO_INPUT_X0_1B_SPARE,
	DIO_INPUT_X0_1C_SPARE,
	DIO_INPUT_X0_1D_SPARE,
	DIO_INPUT_X0_1E_SPARE,
	DIO_INPUT_X0_1F_SPARE,
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_02_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_03_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_04_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_SPARE,
	DIO_OUTPUT_Y0_06_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_07_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_08_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_09_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_0A_TOWERLAMP_BEEP2,
	DIO_OUTPUT_Y0_0B_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_0C_CAMERA_FIX_CYL_ON,
	DIO_OUTPUT_Y0_0D_CAMERA_FIX_CYL_OFF,
	DIO_OUTPUT_Y0_0E_PROBEPIN_CYLINDER_UP,
	DIO_OUTPUT_Y0_0F_PROBEPIN_CYLINDER_DOWN,

	DIO_OUTPUT_Y0_10_DOORLOCK_ONOFF_FRONT,
	DIO_OUTPUT_Y0_11_DOORLOCK_ONOFF_LEFT1,
	DIO_OUTPUT_Y0_12_DOORLOCK_ONOFF_LEFT2,
	DIO_OUTPUT_Y0_13_DOORLOCK_ONOFF_RIGHT1,
	DIO_OUTPUT_Y0_14_DOORLOCK_ONOFF_RIGHT2,
	DIO_OUTPUT_Y0_15_DOORLOCK_ONOFF_BACK1,
	DIO_OUTPUT_Y0_16_DOORLOCK_ONOFF_BACK2,
	DIO_OUTPUT_Y0_17_SPARE,
	DIO_OUTPUT_Y0_18_SPARE,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_1A_SPARE,
	DIO_OUTPUT_Y0_1B_SPARE,
	DIO_OUTPUT_Y0_1C_SPARE,
	DIO_OUTPUT_Y0_1D_SPARE,
	DIO_OUTPUT_Y0_1E_SPARE,
	DIO_OUTPUT_Y0_1F_SPARE,
};
#endif