#pragma once

#include "Def_CompileOption.h"

#if(GET_INSPECTOR == SYS_OQC_SFR_MULTI_CL)
//-------------------------------------------------------------------------
// DIO
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("파워 온"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("초기화 버튼"),
	_T("긴급정지버튼"),
	_T("에어 오프"),
	_T("안전 센서1"),
	_T("-"),
	_T("카메라 감지 센서"),
	_T("-"),
	_T("-"),
	_T("슬립모드 센서"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브핀 내림"),

	_T("도어 인터락 열림/닫힘(전면)"),
	_T("도어 인터락 열림/닫힘(좌측1)"),
	_T("도어 인터락 열림/닫힘(좌측2)"),
	_T("도어 인터락 열림/닫힘(우측1)"),
	_T("도어 인터락 열림/닫힘(우측2)"),
	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("소켓 In"),
	_T("소켓 Out"),
	_T("소켓 올림"),
	_T("소켓 내림"),
};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("Power On"),
	_T("START"),
	_T("STOP"),
	_T("INIT"),
	_T("EMO"),
	_T("Air Down"),
	_T("Area Sensor1"),
	_T("-"),
	_T("Camera Detect Sensor"),
	_T("-"),
	_T("-"),
	_T("Sleep Mode On Sensor"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door Open/Close Sensor(Front)"),
	_T("Door Open/Close Sensor(Left1)"),
	_T("Door Open/Close Sensor(Left2)"),
	_T("Door Open/Close Sensor(Right1)"),
	_T("Door Open/Close Sensor(Right2)"),
	_T("Door Open/Close Sensor(Back1)"),
	_T("Door Open/Close Sensor(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Socket In"),
	_T("Socket Out"),
	_T("Socket Up"),
	_T("Socket Down"),
};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("시작 버튼 램프"),
	_T("정지 버튼 램프"),
	_T("초기화 버튼 램프"),
	_T("리셋 버튼 램프"),
	_T("영상보드 On/Off"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("슬립모드 On"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브 핀 내림"),

	_T("도어 인터락 On/Off(전면)"),
	_T("도어 인터락 On/Off(좌측1)"),
	_T("도어 인터락 On/Off(좌측2)"),
	_T("도어 인터락 On/Off(우측1)"),
	_T("도어 인터락 On/Off(우측2)"),
	_T("도어 인터락 On/Off(후면1)"),
	_T("도어 인터락 On/Off(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("소켓 In"),
	_T("소켓 Out"),
	_T("소켓 올림"),
	_T("소켓 내림"),
};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("START LAMP"),
	_T("STOP LAMP"),
	_T("INIT LAMP"),
	_T("RESET LAMP"),
	_T("-"),
	_T("TOWERLAMP RED"),
	_T("TOWERLAMP YELLOW"),
	_T("TOWERLAMP GREEN"),
	_T("TOWERLAMP BEEP1"),
	_T("TOWERLAMP BEEP2"),
	_T("Sleep Mode On"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door InterLock(Front)"),
	_T("Door InterLock(Left1)"),
	_T("Door InterLock(Left2)"),
	_T("Door InterLock(Right1)"),
	_T("Door InterLock(Right2)"),
	_T("Door InterLock(Bakc1)"),
	_T("Door InterLock(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Socket In"),
	_T("Socket Out"),
	_T("Socket Up"),
	_T("Socekt Down"),
};

// IO LIST INPUT
enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_POWER = 0,
	DIO_INPUT_X0_01_START,
	DIO_INPUT_X0_02_STOP,
	DIO_INPUT_X0_03_INIT,
	DIO_INPUT_X0_04_EMO,
	DIO_INPUT_X0_05_MAINAIR,
	DIO_INPUT_X0_06_AREASENSOR1,
	DIO_INPUT_X0_07_SPARE,
	DIO_INPUT_X0_08_CAMERA_DETECT_SENSOR, //Camera Detect Sensor
	DIO_INPUT_X0_09_SPARE,
	DIO_INPUT_X0_0A_SPARE,
	DIO_INPUT_X0_0B_SLEEPMODE_ON_SENSOR,
	DIO_INPUT_X0_0C_CAMERA_FIX_CYL_ON,
	DIO_INPUT_X0_0D_CAMERA_FIX_CYL_OFF,
	DIO_INPUT_X0_0E_PROBEPIN_UP,
	DIO_INPUT_X0_0F_PROBEPIN_DOWN,

	DIO_INPUT_X0_10_FRONT_DOORLOCK_OPENCLOSE,
	DIO_INPUT_X0_11_LEFT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_12_LEFT_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_13_RIGHT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_14_RIGHT_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_15_BACK_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_16_BACK_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_17_SPARE,
	DIO_INPUT_X0_18_SPARE,
	DIO_INPUT_X0_19_SPARE,
	DIO_INPUT_X0_1A_SPARE,
	DIO_INPUT_X0_1B_SPARE,
	DIO_INPUT_X0_1C_SOCKET_IN,
	DIO_INPUT_X0_1D_SOCKET_OUT,
	DIO_INPUT_X0_1E_SOCKET_UP,
	DIO_INPUT_X0_1F_SOCKET_DOWN,
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_02_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_03_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_04_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_SPARE,
	DIO_OUTPUT_Y0_06_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_07_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_08_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_09_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_0A_TOWERLAMP_BEEP2,
	DIO_OUTPUT_Y0_0B_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_0C_CAMERA_FIX_CYL_ON,
	DIO_OUTPUT_Y0_0D_CAMERA_FIX_CYL_OFF,
	DIO_OUTPUT_Y0_0E_PROBEPIN_CYLINDER_UP,
	DIO_OUTPUT_Y0_0F_PROBEPIN_CYLINDER_DOWN,

	DIO_OUTPUT_Y0_10_DOORLOCK_ONOFF_FRONT,
	DIO_OUTPUT_Y0_11_DOORLOCK_ONOFF_LEFT1,
	DIO_OUTPUT_Y0_12_DOORLOCK_ONOFF_LEFT2,
	DIO_OUTPUT_Y0_13_DOORLOCK_ONOFF_RIGHT1,
	DIO_OUTPUT_Y0_14_DOORLOCK_ONOFF_RIGHT2,
	DIO_OUTPUT_Y0_15_DOORLOCK_ONOFF_BACK1,
	DIO_OUTPUT_Y0_16_DOORLOCK_ONOFF_BACK2,
	DIO_OUTPUT_Y0_17_SPARE,
	DIO_OUTPUT_Y0_18_SPARE,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_1A_SPARE,
	DIO_OUTPUT_Y0_1B_SPARE,
	DIO_OUTPUT_Y0_1C_SOCKET_IN,
	DIO_OUTPUT_Y0_1D_SOCKET_OUT,
	DIO_OUTPUT_Y0_1E_SOCKET_UP,
	DIO_OUTPUT_Y0_1F_SOCKET_DOWN,
};
#elif (GET_INSPECTOR == SYS_OQC_SFR_SINGLE_CL)
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("파워 온"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("초기화 버튼"),
	_T("긴급정지버튼"),
	_T("에어 오프"),
	_T("안전 센서1"),
	_T("-"),
	_T("카메라 감지 센서"),
	_T("-"),
	_T("-"),
	_T("슬립모드 센서"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브핀 내림"),

	_T("도어 인터락 열림/닫힘(전면)"),
	_T("도어 인터락 열림/닫힘(좌측1)"),
	_T("도어 인터락 열림/닫힘(좌측2)"),
	_T("도어 인터락 열림/닫힘(우측1)"),
	_T("도어 인터락 열림/닫힘(우측2)"),
	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("소켓 커버 Open"),
	_T("소켓 In"),
	_T("소켓 Out"),
	_T("소켓 올림"),
	_T("소켓 내림"),
};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("Power On"),
	_T("START"),
	_T("STOP"),
	_T("INIT"),
	_T("EMO"),
	_T("Air Down"),
	_T("Area Sensor1"),
	_T("-"),
	_T("Camera Detect Sensor"),
	_T("-"),
	_T("-"),
	_T("Sleep Mode On Sensor"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door Open/Close Sensor(Front)"),
	_T("Door Open/Close Sensor(Left1)"),
	_T("Door Open/Close Sensor(Left2)"),
	_T("Door Open/Close Sensor(Right1)"),
	_T("Door Open/Close Sensor(Right2)"),
	_T("Door Open/Close Sensor(Back1)"),
	_T("Door Open/Close Sensor(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Socket Cover Open"),
	_T("Socket In"),
	_T("Socket Out"),
	_T("Socket Up"),
	_T("Socket Down"),
};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("시작 버튼 램프"),
	_T("정지 버튼 램프"),
	_T("초기화 버튼 램프"),
	_T("리셋 버튼 램프"),
	_T("영상보드 On/Off"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("슬립모드 On"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브 핀 내림"),

	_T("도어 인터락 On/Off(전면)"),
	_T("도어 인터락 On/Off(좌측1)"),
	_T("도어 인터락 On/Off(우측1)"),
	_T("도어 인터락 On/Off(후면1)"),
	_T("도어 인터락 On/Off(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("소켓 In"),
	_T("소켓 Out"),
	_T("소켓 올림"),
	_T("소켓 내림"),
};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("START LAMP"),
	_T("STOP LAMP"),
	_T("INIT LAMP"),
	_T("RESET LAMP"),
	_T("-"),
	_T("TOWERLAMP RED"),
	_T("TOWERLAMP YELLOW"),
	_T("TOWERLAMP GREEN"),
	_T("TOWERLAMP BEEP1"),
	_T("TOWERLAMP BEEP2"),
	_T("Sleep Mode On"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door InterLock(Front)"),
	_T("Door InterLock(Left1)"),
	_T("Door InterLock(Right1)"),
	_T("Door InterLock(Back1)"),
	_T("Door InterLock(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Socket In"),
	_T("Socket Out"),
	_T("Socket Up"),
	_T("Socekt Down"),
};

// IO LIST INPUT
enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_POWER = 0,
	DIO_INPUT_X0_01_START,
	DIO_INPUT_X0_02_STOP,
	DIO_INPUT_X0_03_INIT,
	DIO_INPUT_X0_04_EMO,
	DIO_INPUT_X0_05_MAINAIR,
	DIO_INPUT_X0_06_AREASENSOR1,
	DIO_INPUT_X0_07_SPARE,
	DIO_INPUT_X0_08_CAMERA_DETECT_SENSOR, //Camera Detect Sensor
	DIO_INPUT_X0_09_SPARE,
	DIO_INPUT_X0_0A_SPARE,
	DIO_INPUT_X0_0B_SLEEPMODE_ON_SENSOR,
	DIO_INPUT_X0_0C_CAMERA_FIX_CYL_ON,
	DIO_INPUT_X0_0D_CAMERA_FIX_CYL_OFF,
	DIO_INPUT_X0_0E_PROBEPIN_UP,
	DIO_INPUT_X0_0F_PROBEPIN_DOWN,

	DIO_INPUT_X0_10_FRONT_DOORLOCK_OPENCLOSE,
	DIO_INPUT_X0_11_LEFT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_12_RIGHT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_13_BACK_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_14_BACK_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_15_SPARE,
	DIO_INPUT_X0_16_SPARE,
	DIO_INPUT_X0_17_SPARE,
	DIO_INPUT_X0_18_SPARE,
	DIO_INPUT_X0_19_SPARE,
	DIO_INPUT_X0_1A_SPARE,
	DIO_INPUT_X0_1B_SOCKET_COVER_OPEN,
	DIO_INPUT_X0_1C_SOCKET_IN,
	DIO_INPUT_X0_1D_SOCKET_OUT,
	DIO_INPUT_X0_1E_SOCKET_UP,
	DIO_INPUT_X0_1F_SOCKET_DOWN,
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_02_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_03_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_04_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_SPARE,
	DIO_OUTPUT_Y0_06_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_07_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_08_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_09_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_0A_TOWERLAMP_BEEP2,
	DIO_OUTPUT_Y0_0B_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_0C_CAMERA_FIX_CYL_ON,
	DIO_OUTPUT_Y0_0D_CAMERA_FIX_CYL_OFF,
	DIO_OUTPUT_Y0_0E_PROBEPIN_CYLINDER_UP,
	DIO_OUTPUT_Y0_0F_PROBEPIN_CYLINDER_DOWN,

	DIO_OUTPUT_Y0_10_DOORLOCK_ONOFF_FRONT,
	DIO_OUTPUT_Y0_11_DOORLOCK_ONOFF_LEFT1,
	DIO_OUTPUT_Y0_12_DOORLOCK_ONOFF_RIGHT1,
	DIO_OUTPUT_Y0_13_DOORLOCK_ONOFF_BACK1,
	DIO_OUTPUT_Y0_14_DOORLOCK_ONOFF_BACK2,
	DIO_OUTPUT_Y0_15_SPARE,
	DIO_OUTPUT_Y0_16_SPARE,
	DIO_OUTPUT_Y0_17_SPARE,
	DIO_OUTPUT_Y0_18_SPARE,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_1A_SPARE,
	DIO_OUTPUT_Y0_1B_SPARE,
	DIO_OUTPUT_Y0_1C_SOCKET_IN,
	DIO_OUTPUT_Y0_1D_SOCKET_OUT,
	DIO_OUTPUT_Y0_1E_SOCKET_UP,
	DIO_OUTPUT_Y0_1F_SOCKET_DOWN,
};
// IO Dlg End
//-------------------------------------------------------------------------
#elif (GET_INSPECTOR == SYS_DISTORTION_30)
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("파워 온"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("초기화 버튼"),
	_T("긴급정지버튼"),
	_T("에어 오프"),
	_T("안전 센서1"),
	_T("-"),
	_T("소켓 열림/닫힘 센서1"),
	_T("소켓 열림/닫힘 센서2"),
	_T("-"),
	_T("슬립모드 센서"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브핀 내림"),

	_T("도어 인터락 열림/닫힘(전면)"),
	_T("도어 인터락 열림/닫힘(좌측1)"),
	_T("도어 인터락 열림/닫힘(좌측2)"),
	_T("도어 인터락 열림/닫힘(우측1)"),
	_T("도어 인터락 열림/닫힘(우측2)"),
	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("Power On"),
	_T("START"),
	_T("STOP"),
	_T("INIT"),
	_T("EMO"),
	_T("Air Down"),
	_T("Area Sensor1"),
	_T("-"),
	_T("Manual Socket Open/Close1"),
	_T("Manual Socket Open/Close2"),
	_T("-"),
	_T("Sleep Mode On Sensor"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door Open/Close Sensor(Front)"),
	_T("Door Open/Close Sensor(Left1)"),
	_T("Door Open/Close Sensor(Left2)"),
	_T("Door Open/Close Sensor(Right1)"),
	_T("Door Open/Close Sensor(Right2)"),
	_T("Door Open/Close Sensor(Back1)"),
	_T("Door Open/Close Sensor(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("시작 버튼 램프"),
	_T("정지 버튼 램프"),
	_T("초기화 버튼 램프"),
	_T("리셋 버튼 램프"),
	_T("-"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("슬립모드 On"),
	_T("카메라 고정 실린더 On"),
	_T("카메라 고정 실린더 Off"),
	_T("프로브 핀 올림"),
	_T("프로브 핀 내림"),

	_T("도어 인터락 On/Off(전면)"),
	_T("도어 인터락 On/Off(좌측1)"),
	_T("도어 인터락 On/Off(좌측2)"),
	_T("도어 인터락 On/Off(우측1)"),
	_T("도어 인터락 On/Off(우측2)"),
	_T("도어 인터락 On/Off(후면1)"),
	_T("도어 인터락 On/Off(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("START LAMP"),
	_T("STOP LAMP"),
	_T("INIT LAMP"),
	_T("RESET LAMP"),
	_T("-"),
	_T("TOWERLAMP RED"),
	_T("TOWERLAMP YELLOW"),
	_T("TOWERLAMP GREEN"),
	_T("TOWERLAMP BEEP1"),
	_T("TOWERLAMP BEEP2"),
	_T("Sleep Mode On"),
	_T("Camera Fix Cyl. On"),
	_T("Camera Fix Cyl. Off"),
	_T("Probe Pin Up"),
	_T("Probe Pin Down"),

	_T("Door InterLock(Front)"),
	_T("Door InterLock(Left1)"),
	_T("Door InterLock(Left2)"),
	_T("Door InterLock(Right1)"),
	_T("Door InterLock(Right2)"),
	_T("Door InterLock(Bakc1)"),
	_T("Door InterLock(Back2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
};

// IO LIST INPUT
enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_POWER = 0,
	DIO_INPUT_X0_01_START,
	DIO_INPUT_X0_02_STOP,
	DIO_INPUT_X0_03_INIT,
	DIO_INPUT_X0_04_EMO,
	DIO_INPUT_X0_05_MAINAIR,
	DIO_INPUT_X0_06_AREASENSOR1,
	DIO_INPUT_X0_07_SPARE,
	DIO_INPUT_X0_08_MANUALSOCEKT_OPENCLOSE1,
	DIO_INPUT_X0_09_MANUALSOCEKT_OPENCLOSE2,
	DIO_INPUT_X0_0A_SPARE,
	DIO_INPUT_X0_0B_SLEEPMODE_ON_SENSOR,
	DIO_INPUT_X0_0C_CAMERA_FIX_CYL_ON,
	DIO_INPUT_X0_0D_CAMERA_FIX_CYL_OFF,
	DIO_INPUT_X0_0E_PROBEPIN_UP,
	DIO_INPUT_X0_0F_PROBEPIN_DOWN,

	DIO_INPUT_X0_10_FRONT_DOORLOCK_OPENCLOSE,
	DIO_INPUT_X0_11_LEFT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_12_LEFT_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_13_RIGHT_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_14_RIGHT_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_15_BACK_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_16_BACK_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_17_SPARE,
	DIO_INPUT_X0_18_SPARE,
	DIO_INPUT_X0_19_SPARE,
	DIO_INPUT_X0_1A_SPARE,
	DIO_INPUT_X0_1B_SPARE,
	DIO_INPUT_X0_1C_SPARE,
	DIO_INPUT_X0_1D_SPARE,
	DIO_INPUT_X0_1E_SPARE,
	DIO_INPUT_X0_1F_SPARE,
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_02_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_03_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_04_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_SPARE,
	DIO_OUTPUT_Y0_06_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_07_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_08_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_09_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_0A_TOWERLAMP_BEEP2,
	DIO_OUTPUT_Y0_0B_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_0C_CAMERA_FIX_CYL_ON,
	DIO_OUTPUT_Y0_0D_CAMERA_FIX_CYL_OFF,
	DIO_OUTPUT_Y0_0E_PROBEPIN_CYLINDER_UP,
	DIO_OUTPUT_Y0_0F_PROBEPIN_CYLINDER_DOWN,

	DIO_OUTPUT_Y0_10_DOORLOCK_ONOFF_FRONT,
	DIO_OUTPUT_Y0_11_DOORLOCK_ONOFF_LEFT1,
	DIO_OUTPUT_Y0_12_DOORLOCK_ONOFF_LEFT2,
	DIO_OUTPUT_Y0_13_DOORLOCK_ONOFF_RIGHT1,
	DIO_OUTPUT_Y0_14_DOORLOCK_ONOFF_RIGHT2,
	DIO_OUTPUT_Y0_15_DOORLOCK_ONOFF_BACK1,
	DIO_OUTPUT_Y0_16_DOORLOCK_ONOFF_BACK2,
	DIO_OUTPUT_Y0_17_SPARE,
	DIO_OUTPUT_Y0_18_SPARE,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_1A_SPARE,
	DIO_OUTPUT_Y0_1B_SPARE,
	DIO_OUTPUT_Y0_1C_SPARE,
	DIO_OUTPUT_Y0_1D_SPARE,
	DIO_OUTPUT_Y0_1E_SPARE,
	DIO_OUTPUT_Y0_1F_SPARE,
};
//kimuh	I/O
#elif (GET_INSPECTOR == SYS_FILM_PEEL_OFF)
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("파워 온"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("초기화 버튼"),
	_T("긴급정지버튼"),
	_T("에어 오프"),
	_T("안전 센서1"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("슬립모드 센서"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),

	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("[그립퍼]필름 박스 감지 1"),
	_T("[그립퍼]필름 박스 감지 2"),
	_T("-"),
	_T("-"),
	_T("[소켓 스테이지] PCB 필름 좌측 감지"),
	_T("[소켓 스테이지] PCB 필름 우측 감지"),
	_T("-"),
	_T("[소켓 스테이지] 작업 영역 감지"),
	_T("-"),
	_T("[소켓 스테이지] PCB 감지"),

	_T("[그립퍼]필름 그립퍼 상단 실린더 좌측"),
	_T("[그립퍼]필름 그립퍼 하단 실린더 좌측"),
	_T("[그립퍼]필름 그립퍼 상단 실린더 우측"),
	_T("[그립퍼]필름 그립퍼 하단 실린더 우측"),
	_T("-"),
	_T("-"),
	_T("[그립퍼] 그립퍼 전진 실린더 좌측 "),
	_T("[그립퍼] 그립퍼 후진 실린더 좌측"),
	_T("[그립퍼] 그립퍼 전진 실린더 우측"),
	_T("[그립퍼] 그립퍼 후진 실린더 우측"),
	_T("-"),
	_T("-"),
	_T("[그립퍼] 덮개 상단 실린더 좌측"),
	_T("[그립퍼] 덮개 하단 실린더 좌측"),
	_T("[그립퍼] 덮개 상단 실린더 우측"),
	_T("[그립퍼] 덮개 하단 실린더 우측"),

	_T("-"),
	_T("-"),
	_T("[그립퍼]필름 잡기 닫힘 실린더"),
	_T("[그립퍼]필름 잡기 풀림 실린더"),
	_T("[그립퍼]필름 잡기 상단 실린더"),
	_T("[그립퍼]필름 잡기 하단 실린더"),
	_T("[IZN10E] 이온아이저 이온검사 좌측"),
	_T("[IZN10E] 이온아이저 오류검사 좌측"),
	_T("[IZN10E] 이온아이저 정비확인 좌측"),
	_T("-"),
	_T("[IZN10E] 이온아이저 이온검사 우측"),
	_T("[IZN10E] 이온아이저 오류검사 우측"),
	_T("[IZN10E] 이온아이저 정비확인 우측"),
	_T("-"),
	_T("[렌즈 덮개 밀폐기]필름 그립퍼 상단 실린더"),
	_T("[렌즈 덮개 밀폐기]필름 그립퍼 하단 실린더"),
};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("Power On"),
	_T("START"),
	_T("STOP"),
	_T("INIT"),
	_T("EMO"),
	_T("Air Down"),
	_T("Area Sensor1"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Sleep Mode On Sensor"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),

	_T("Door Open/Close Sensor(Rear1)"),
	_T("Door Open/Close Sensor(Rear2)"),
	_T("Door Open/Close Sensor(Rear3)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("[Gripper] Flim Box Detect Sensor 1"),
	_T("[Gripper] Flim Box Detect Sensor 2"),
	_T("-"),
	_T("-"),
	_T("[Socket Stage] PCB Film Dtc Snr Left"),
	_T("[Socket Stage] PCB Film Dtc Snr Right"),
	_T("-"),
	_T("[Socket Stage] Work Zone Area Sensor"),
	_T("-"),
	_T("[Socket Stage] PCB Derctector Sensor"),

	_T("[Gripper] Flim Gripper Cyl On Left"),
	_T("[Gripper] Flim Gripper Cyl Off Left"),
	_T("[Gripper] Flim Gripper Cyl On Right"),
	_T("[Gripper] Flim Gripper Cyl Off Right"),
	_T("-"),
	_T("-"),
	_T("[Gripper] Gripper Front Cyl Left"),
	_T("[Gripper] Gripper Rear Cyl Left"),
	_T("[Gripper] Gripper Front Cyl Right"),
	_T("[Gripper] Gripper Rear Cyl Right"),
	_T("-"),
	_T("-"),
	_T("[Gripper] Cover Cyl On Left"),
	_T("[Gripper] Cover Cyl Off Left"),
	_T("[Gripper] Cover Cyl On Right"),
	_T("[Gripper] Cover Cyl Off Right"),

	_T("-"),
	_T("-"),
	_T("[Socket Stage] PCB Gripper Close(On)"),
	_T("[Socket Stage] PCB Gripper Open(Off)"),
	_T("[Socket Stage] PCB Gripper Up(On)"),
	_T("[Socket Stage] PCB Gripper Down(Off)"),
	_T("[IZN10E] Ionizer Ion Check Left"),
	_T("[IZN10E] Ionizer Error Check Left"),
	_T("[IZN10E] Ionizer Maintenance Check Left"),
	_T("-"),
	_T("[IZN10E] Ionizer Ion Check Right"),
	_T("[IZN10E] Ionizer Error Check Right"),
	_T("[IZN10E] Ionizer Maintenance Check Right"),
	_T("-"),
	_T("[Lens Cover Push] Up/Down Cyl Up"),
	_T("[Lens Cover Push] Up/Down Cyl Down"),
};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("시작 버튼 램프"),
	_T("정지 버튼 램프"),
	_T("초기화 버튼 램프"),
	_T("리셋 버튼 램프"),
	_T("-"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("슬립모드 On"),
	_T("-"),
	_T("-"),
	_T("대기모드"),
	_T("-"),

	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면1)"),
	_T("도어 인터락 열림/닫힘(후면2)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("[그립퍼]필름 박스 감지 1"),
	_T("[그립퍼]필름 박스 감지 2"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	
	_T("[그립퍼]필름 그립퍼 상단 실린더 좌측"),
	_T("[그립퍼]필름 그립퍼 하단 실린더 좌측"),
	_T("[그립퍼]필름 그립퍼 상단 실린더 우측"),
	_T("[그립퍼]필름 그립퍼 하단 실린더 우측"),
	_T("-"),
	_T("-"),
	_T("[그립퍼] 그립퍼 전진 실린더 좌측 "),
	_T("[그립퍼] 그립퍼 후진 실린더 좌측"),
	_T("[그립퍼] 그립퍼 전진 실린더 우측"),
	_T("[그립퍼] 그립퍼 후진 실린더 우측"),
	_T("-"),
	_T("-"),
	_T("[그립퍼] 덮개 상단 실린더 좌측"),
	_T("[그립퍼] 덮개 하단 실린더 좌측"),
	_T("[그립퍼] 덮개 상단 실린더 우측"),
	_T("[그립퍼] 덮개 하단 실린더 우측"),

	_T("-"),
	_T("-"),
	_T("[그립퍼]필름 잡기 닫힘 실린더"),
	_T("[그립퍼]필름 잡기 풀림 실린더"),
	_T("[그립퍼]필름 잡기 상단 실린더"),
	_T("[그립퍼]필름 잡기 하단 실린더"),
	_T("[IZN10E] 이온아이저 전원 동작/ 비동작 좌측"),
	_T("[IZN10E] 이온아이저 이온 동작/ 비동작 좌측"),
	_T("[IZN10E] 이온아이저 재시작 좌측"),
	_T("-"),
	_T("[IZN10E] 이온아이저 전원 동작/ 비동작 우측"),
	_T("[IZN10E] 이온아이저 이온 동작/ 비동작 우측"),
	_T("[IZN10E] 이온아이저 재시작 우측"),
	_T("-"),
	_T("[렌즈 덮개 밀폐기]필름 그립퍼 상단 실린더"),
	_T("[렌즈 덮개 밀폐기]필름 그립퍼 하단 실린더"),
};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("START LAMP"),
	_T("STOP LAMP"),
	_T("INIT LAMP"),
	_T("RESET LAMP"),
	_T("-"),
	_T("TOWERLAMP RED"),
	_T("TOWERLAMP YELLOW"),
	_T("TOWERLAMP GREEN"),
	_T("TOWERLAMP BEEP1"),
	_T("-"),
	_T("Sleep Mode On"),
	_T("-"),
	_T("-"),
	_T("MUTING"),
	_T("-"),

	_T("Door Open/Close Sensor(Rear1)"),
	_T("Door Open/Close Sensor(Rear2)"),
	_T("Door Open/Close Sensor(Rear3)"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("[Gripper] Flim Box Detect Sensor 1"),
	_T("[Gripper] Flim Box Detect Sensor 2"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),
	_T("-"),

	_T("[Gripper] Flim Gripper Cyl On Left"),
	_T("[Gripper] Flim Gripper Cyl Off Left"),
	_T("[Gripper] Flim Gripper Cyl On Right"),
	_T("[Gripper] Flim Gripper Cyl Off Right"),
	_T("-"),
	_T("-"),
	_T("[Gripper] Gripper Front Cyl Left"),
	_T("[Gripper] Gripper Rear Cyl Left"),
	_T("[Gripper] Gripper Front Cyl Right"),
	_T("[Gripper] Gripper Rear Cyl Right"),
	_T("-"),
	_T("-"),
	_T("[Gripper] Cover Cyl On Left"),
	_T("[Gripper] Cover Cyl Off Left"),
	_T("[Gripper] Cover Cyl On Right"),
	_T("[Gripper] Cover Cyl Off Right"),

	_T("-"),
	_T("-"),
	_T("[Socket Stage] PCB Gripper Close(On)"),
	_T("[Socket Stage] PCB Gripper Open(Off)"),
	_T("[Socket Stage] PCB Gripper Up(On)"),
	_T("[Socket Stage] PCB Gripper Down(Off)"),
	_T("[IZN10E] Ionizer Power On / Off Left"),
	_T("[IZN10E] Ionizer Ion On / Off Left"),
	_T("[IZN10E] Ionizer Reset Left"),
	_T("-"),
	_T("[IZN10E] Ionizer Power On / Off Right"),
	_T("[IZN10E] Ionizer Ion On / Off Right"),
	_T("[IZN10E] Ionizer Reset Right"),
	_T("-"),
	_T("[Lens Cover Push] Up/Down Cyl Up"),
	_T("[Lens Cover Push] Up/Down Cyl Down"),
};

// IO LIST INPUT
enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_POWER = 0,
	DIO_INPUT_X0_01_START,
	DIO_INPUT_X0_02_STOP,
	DIO_INPUT_X0_03_INIT,
	DIO_INPUT_X0_04_EMO,
	DIO_INPUT_X0_05_MAINAIR,
	DIO_INPUT_X0_06_AREASENSOR1,
	DIO_INPUT_X0_07_SPARE,
	DIO_INPUT_X0_08_SPARE,
	DIO_INPUT_X0_09_SPARE,
	DIO_INPUT_X0_10_SPARE,
	DIO_INPUT_X0_11_SLEEPMODE_ON_SENSOR,
	DIO_INPUT_X0_12_SPARE,
	DIO_INPUT_X0_13_SPARE,
	DIO_INPUT_X0_14_SPARE,
	DIO_INPUT_X0_15_SPARE,

	DIO_INPUT_X0_16_REAR_DOORLOCK1_OPENCLOSE,
	DIO_INPUT_X0_17_REAR_DOORLOCK2_OPENCLOSE,
	DIO_INPUT_X0_18_REAR_DOORLOCK3_OPENCLOSE,
	DIO_INPUT_X0_19_SPARE,
	DIO_INPUT_X0_20_SPARE,
	DIO_INPUT_X0_21_SPARE,
	DIO_INPUT_X0_22_GRIPPER_UNIT_FILM_BOX_DETECT_SENSOR_LEFT,
	DIO_INPUT_X0_23_GRIPPER_UNIT_FILM_BOX_DETECT_SENSOR_RIGHT,
	DIO_INPUT_X0_24_SPARE,
	DIO_INPUT_X0_25_SPARE,
	DIO_INPUT_X0_26_SOCKET_STAGE_UNIT_PCB_FILM_DETECTOR_SENSOR_LEFT,
	DIO_INPUT_X0_27_SOCKET_STAGE_UNIT_PCB_FILM_DETECTOR_SENSOR_RIGHT,
	DIO_INPUT_X0_28_SPARE,
	DIO_INPUT_X0_29_SOCKET_STAGE_UNIT_WORK_ZONE_AREA_SENSOR,
	DIO_INPUT_X0_30_SPARE,
	DIO_INPUT_X0_31_SOCKET_STAGE_UNIT_PCB_DETECTOR_SENSOR,

	DIO_INPUT_X1_00_GRIPPER_UNIT_FILM_GRIPPER_CYLINDER_ON_LEFT,
	DIO_INPUT_X1_01_GRIPPER_UNIT_FILM_GRIPPER_CYLINDER_OFF_LEFT,
	DIO_INPUT_X1_02_GRIPPER_UNIT_FILM_GRIPPER_CYLINDER_ON_RIGHT,
	DIO_INPUT_X1_03_GRIPPER_UNIT_FILM_GRIPPER_CYLINDER_OFF_RIGHT,
	DIO_INPUT_X1_04_SPARE,
	DIO_INPUT_X1_05_SPARE,
	DIO_INPUT_X1_06_GRIPPER_UNIT_GRIPPER_FRONT_CYLINDER_LEFT,
	DIO_INPUT_X1_07_GRIPPER_UNIT_GRIPPER_REAR_CYLINDER_LEFT,
	DIO_INPUT_X1_08_GRIPPER_UNIT_GRIPPER_FRONT_CYLINDER_RIGHT,
	DIO_INPUT_X1_09_GRIPPER_UNIT_GRIPPER_REAR_CYLINDER_RIGHT,
	DIO_INPUT_X1_10_SPARE,
	DIO_INPUT_X1_11_SPARE,
	DIO_INPUT_X1_12_GRIPPER_UNIT_COVER_GRIPPER_CYLINDER_ON_LEFT,
	DIO_INPUT_X1_13_GRIPPER_UNIT_COVER_GRIPPER_CYLINDER_OFF_LEFT,
	DIO_INPUT_X1_14_GRIPPER_UNIT_COVER_GRIPPER_CYLINDER_ON_RIGHT,
	DIO_INPUT_X1_15_GRIPPER_UNIT_COVER_GRIPPER_CYLINDER_OFF_RIGHT,

	DIO_INPUT_X1_16_SPARE,
	DIO_INPUT_X1_17_SPARE,
	DIO_INPUT_X1_18_SOCKET_STAGE_UNIT_PCB_GRIPPER_CYLINDER_CLOSE_ON,
	DIO_INPUT_X1_19_SOCKET_STAGE_UNIT_PCB_GRIPPER_CYLINDER_OPEN_OFF,
	DIO_INPUT_X1_20_SOCKET_STAGE_UNIT_PCB_GRIPPER_CYLINDER_UP,
	DIO_INPUT_X1_21_SOCKET_STAGE_UNIT_PCB_GRIPPER_CYLINDER_DOWN,
	DIO_INPUT_X1_22_IONIZER_UNIT_ION_CHECK_LEFT,
	DIO_INPUT_X1_23_IONIZER_UNIT_ERROR_CHECK_LEFT,
	DIO_INPUT_X1_24_IONIZER_UNIT_MAINTENANCE_CHECK_LEFT,
	DIO_INPUT_X1_25_SPARE,
	DIO_INPUT_X1_26_IONIZER_UNIT_ION_CHECK_RIGHT,
	DIO_INPUT_X1_27_IONIZER_UNIT_ERROR_CHECK_RIGHT,
	DIO_INPUT_X1_28_IONIZER_UNIT_MAINTENANCE_CHECK_RIGHT,
	DIO_INPUT_X1_29_SPARE,
	DIO_INPUT_X1_30_LENS_COVER_PUSH_UNIT_UPDOWN_GRIPPER_CYLINDER_UP,
	DIO_INPUT_X1_31_LENS_COVER_PUSH_UNIT_UPDOWN_GRIPPER_CYLINDER_DOWN,
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_02_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_03_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_04_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_SPARE,
	DIO_OUTPUT_Y0_06_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_07_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_08_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_09_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_10_SPARE,
	DIO_OUTPUT_Y0_11_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_12_SPARE,
	DIO_OUTPUT_Y0_13_MUTING,
	DIO_OUTPUT_Y0_14_SPARE,
	DIO_OUTPUT_Y0_15_SPARE,

	DIO_OUTPUT_Y0_16_REAR_DOORLOCK1_OPENCLOSE,
	DIO_OUTPUT_Y0_17_REAR_DOORLOCK2_OPENCLOSE,
	DIO_OUTPUT_Y0_18_REAR_DOORLOCK3_OPENCLOSE,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_20_SPARE,
	DIO_OUTPUT_Y0_21_SPARE,
	DIO_OUTPUT_Y0_22_GRIPPER_UNIT_AIR_BLOW_UNIT_LEFT,
	DIO_OUTPUT_Y0_23_GRIPPER_UNIT_AIR_BLOW_UNIT_RIGHT,
	DIO_OUTPUT_Y0_24_SPARE,
	DIO_OUTPUT_Y0_25_SPARE,
	DIO_OUTPUT_Y0_26_SPARE,
	DIO_OUTPUT_Y0_27_SPARE,
	DIO_OUTPUT_Y0_28_SPARE,
	DIO_OUTPUT_Y0_29_SPARE,
	DIO_OUTPUT_Y0_30_SPARE,
	DIO_OUTPUT_Y0_31_SPARE,

	DIO_OUTPUT_Y1_00_GRIPPER_UNIT_FILM_GRIPPER_CYLINDER_ON_LEFT,
	DIO_OUTPUT_Y1_01_GRIPPER_UNIT_FILM_GRIPPER_CYLINDER_OFF_LEFT,
	DIO_OUTPUT_Y1_02_GRIPPER_UNIT_FILM_GRIPPER_CYLINDER_ON_RIGHT,
	DIO_OUTPUT_Y1_03_GRIPPER_UNIT_FILM_GRIPPER_CYLINDER_OFF_RIGHT,
	DIO_OUTPUT_Y1_04_SPARE,
	DIO_OUTPUT_Y1_05_SPARE,
	DIO_OUTPUT_Y1_06_GRIPPER_UNIT_GRIPPER_FRONT_CYLINDER_LEFT,
	DIO_OUTPUT_Y1_07_GRIPPER_UNIT_GRIPPER_REAR_CYLINDER_LEFT,
	DIO_OUTPUT_Y1_08_GRIPPER_UNIT_GRIPPER_FRONT_CYLINDER_RIGHT,
	DIO_OUTPUT_Y1_09_GRIPPER_UNIT_GRIPPER_REAR_CYLINDER_RIGHT,
	DIO_OUTPUT_Y1_10_SPARE,
	DIO_OUTPUT_Y1_11_SPARE,
	DIO_OUTPUT_Y1_12_GRIPPER_UNIT_COVER_GRIPPER_CYLINDER_ON_LEFT,
	DIO_OUTPUT_Y1_13_GRIPPER_UNIT_COVER_GRIPPER_CYLINDER_OFF_LEFT,
	DIO_OUTPUT_Y1_14_GRIPPER_UNIT_COVER_GRIPPER_CYLINDER_ON_RIGHT,
	DIO_OUTPUT_Y1_15_GRIPPER_UNIT_COVER_GRIPPER_CYLINDER_OFF_RIGHT,

	DIO_OUTPUT_Y1_16_SPARE,
	DIO_OUTPUT_Y1_17_SPARE,
	DIO_OUTPUT_Y1_18_SOCKET_STAGE_UNIT_PCB_GRIPPER_CYLINDER_CLOSE_ON,
	DIO_OUTPUT_Y1_19_SOCKET_STAGE_UNIT_PCB_GRIPPER_CYLINDER_OPEN_OFF,
	DIO_OUTPUT_Y1_20_SOCKET_STAGE_UNIT_PCB_GRIPPER_CYLINDER_UP,
	DIO_OUTPUT_Y1_21_SOCKET_STAGE_UNIT_PCB_GRIPPER_CYLINDER_DOWN,
	DIO_OUTPUT_Y1_22_IONIZER_UNIT_POWER_ONOFF_LEFT,
	DIO_OUTPUT_Y1_23_IONIZER_UNIT_ION_ONOFF_LEFT,
	DIO_OUTPUT_Y1_24_IONIZER_UNIT_RESET_LEFT,
	DIO_OUTPUT_Y1_25_SPARE,
	DIO_OUTPUT_Y1_26_IONIZER_UNIT_POWER_ONOFF_RIGHT,
	DIO_OUTPUT_Y1_27_IONIZER_UNIT_ION_ONOFF_RIGHT,
	DIO_OUTPUT_Y1_28_IONIZER_UNIT_RESET_RIGHT,
	DIO_OUTPUT_Y1_29_SPARE,
	DIO_OUTPUT_Y1_30_LENS_COVER_PUSH_UNIT_UPDOWN_GRIPPER_CYLINDER_UP,
	DIO_OUTPUT_Y1_31_LENS_COVER_PUSH_UNIT_UPDOWN_GRIPPER_CYLINDER_DOWN,
};
#endif